using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// NOTE: This file should be generated by the Source Generator in the future
namespace MetaJson
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property)]
    internal sealed class SerializeAttribute: Attribute
    {
        
    }
}
